const GENERAL_COMMON_PHRASES = [
  ['천천히 말씀해 주세요', 'Xin vui lòng nói chậm hơn.', 'cheon-cheon-hi mal-sseum-hae ju-se-yo'],
  ['한 번 더 말씀해 주세요', 'Xin vui lòng nói lại một lần nữa.', 'han beon deo mal-sseum-hae ju-se-yo'],
  ['이쪽으로 와 주세요', 'Xin mời đi hướng này.', 'i-jjok-eu-ro wa ju-se-yo'],
  ['잠시만 기다려 주세요', 'Xin vui lòng chờ một chút.', 'jam-si-man gi-da-ryeo ju-se-yo'],
  ['괜찮으세요?', 'Quý khách có ổn không?', 'gwaen-chanh-eu-se-yo'],
  ['불편한 점이 있으세요?', 'Quý khách có điều gì bất tiện không?', 'bul-pyeon-han jeom-i i-sseu-se-yo'],
  ['도와드릴까요?', 'Tôi có thể hỗ trợ quý khách không?', 'do-wa-deu-ril-kka-yo'],
  ['네, 맞습니다', 'Vâng, đúng rồi ạ.', 'ne mat-seum-ni-da'],
  ['아니요, 아닙니다', 'Không, không phải vậy ạ.', 'a-ni-yo a-nim-ni-da'],
  ['감사합니다', 'Cảm ơn quý khách.', 'gam-sa-ham-ni-da'],
  ['죄송합니다', 'Xin lỗi quý khách.', 'joe-song-ham-ni-da'],
  ['실례합니다', 'Xin phép / làm phiền một chút.', 'sil-lye-ham-ni-da'],
  ['지금 출발하겠습니다', 'Bây giờ chúng ta sẽ khởi hành.', 'ji-geum chul-bal-ha-ge-sseum-ni-da'],
  ['곧 도착합니다', 'Chúng ta sắp đến nơi.', 'got do-chak-ham-ni-da'],
  ['사진 찍어 드릴까요?', 'Tôi chụp ảnh giúp quý khách nhé?', 'sa-jin jji-geo deu-ril-kka-yo'],
  ['여기에서 잠시 쉬겠습니다', 'Chúng ta nghỉ ngắn tại đây.', 'yeo-gi-e-seo jam-si swi-ge-sseum-ni-da'],
  ['화장실은 저쪽에 있습니다', 'Nhà vệ sinh ở phía bên kia.', 'hwa-jang-sil-eun jeo-jjok-e i-sseum-ni-da'],
  ['물 필요하시면 말씀해 주세요', 'Nếu cần nước, xin báo tôi.', 'mul pi-ryo-ha-si-myeon mal-sseum-hae ju-se-yo'],
  ['오늘 날씨가 덥습니다', 'Hôm nay thời tiết khá nóng.', 'o-neul nal-ssi-ga deop-seum-ni-da'],
  ['오늘 날씨가 쌀쌀합니다', 'Hôm nay thời tiết hơi lạnh.', 'o-neul nal-ssi-ga ssal-ssal-ham-ni-da'],
  ['우산을 챙겨 주세요', 'Xin nhớ mang theo ô.', 'u-san-eul chaeng-gyeo ju-se-yo'],
  ['분실물 없으세요?', 'Quý khách có quên đồ gì không?', 'bun-sil-mul eop-seu-se-yo'],
  ['가방을 잘 챙겨 주세요', 'Xin giữ kỹ hành lý.', 'ga-bang-eul jal chaeng-gyeo ju-se-yo'],
  ['안전이 가장 중요합니다', 'An toàn là quan trọng nhất.', 'an-jeon-i ga-jang jung-yo-ham-ni-da'],
  ['일정이 조금 변경되었습니다', 'Lịch trình có thay đổi một chút.', 'il-jeong-i jo-geum byeon-gyeong-doe-eot-seum-ni-da'],
  ['시간이 조금 늦어지고 있습니다', 'Chúng ta đang trễ nhẹ về thời gian.', 'si-gan-i jo-geum neu-jeo-ji-go i-sseum-ni-da'],
  ['서둘러 주시면 감사하겠습니다', 'Nếu quý khách nhanh giúp tôi sẽ rất cảm ơn.', 'seo-du-lleo ju-si-myeon gam-sa-ha-ge-sseum-ni-da'],
  ['여기서 모이겠습니다', 'Chúng ta sẽ tập trung tại đây.', 'yeo-gi-seo mo-i-ge-sseum-ni-da'],
  ['이 번호로 연락해 주세요', 'Xin liên hệ số này giúp tôi.', 'i beo-no-ro yeol-lak-hae ju-se-yo'],
  ['한국어가 천천히 가능합니다', 'Tôi nói tiếng Hàn chậm sẽ tốt hơn.', 'han-gu-geo-ga cheon-cheon-hi ga-neung-ham-ni-da'],
  ['베트남어 통역이 필요하시면 말씀해 주세요', 'Nếu cần phiên dịch tiếng Việt, xin báo tôi.', 'be-teu-nam-eo tong-yeok-i pi-ryo-ha-si-myeon mal-sseum-hae ju-se-yo'],
  ['사진 시간은 십 분입니다', 'Thời gian chụp ảnh là 10 phút.', 'sa-jin si-gan-eun sip bun-im-ni-da'],
  ['음료는 차 안에서만 드세요', 'Xin chỉ uống nước trong xe.', 'eum-ryo-neun cha an-e-seo-man deu-se-yo'],
  ['쓰레기는 제가 수거하겠습니다', 'Tôi sẽ gom rác giúp quý khách.', 'sseu-re-gi-neun je-ga su-geo-ha-ge-sseum-ni-da'],
  ['핸드폰 배터리를 확인해 주세요', 'Xin kiểm tra pin điện thoại.', 'haen-deu-pon bae-teo-ri-reul hwa-gin-hae ju-se-yo'],
  ['현금과 카드를 함께 준비해 주세요', 'Xin chuẩn bị cả tiền mặt và thẻ.', 'hyeon-geum-gwa ka-deu-reul ham-kke jun-bi-hae ju-se-yo'],
  ['영수증을 꼭 받아 주세요', 'Xin nhớ nhận hóa đơn.', 'yeong-su-jeung-eul kkok ba-da ju-se-yo'],
  ['잠시 후 자유시간입니다', 'Sắp tới là thời gian tự do.', 'jam-si hu ja-yu-si-gan-im-ni-da'],
  ['다시 모이는 시간은 네 시입니다', 'Giờ tập trung lại là 4 giờ.', 'da-si mo-i-neun si-gan-eun ne si-im-ni-da'],
  ['궁금한 점 있으시면 질문해 주세요', 'Nếu có thắc mắc xin cứ hỏi.', 'gung-geum-han jeom i-sseu-si-myeon jil-mun-hae ju-se-yo'],
  ['오늘 일정 정말 수고 많으셨습니다', 'Hôm nay quý khách đã rất vất vả rồi.', 'o-neul il-jeong jeong-mal su-go manh-eu-syeot-seum-ni-da'],
  ['다음 장소로 이동하겠습니다', 'Chúng ta sẽ di chuyển sang điểm kế tiếp.', 'da-eum jang-so-ro i-dong-ha-ge-sseum-ni-da'],
  ['휴식 시간은 이십 분입니다', 'Thời gian nghỉ là 20 phút.', 'hyu-sik si-gan-eun i-sip bun-im-ni-da'],
  ['사진 찍고 바로 오겠습니다', 'Chụp xong tôi quay lại ngay.', 'sa-jin jjik-go ba-ro o-ge-sseum-ni-da'],
  ['안내 방송을 들어 주세요', 'Xin lắng nghe thông báo hướng dẫn.', 'an-nae bang-song-eul deu-reo ju-se-yo'],
  ['좌석 번호를 확인해 주세요', 'Xin kiểm tra số ghế.', 'jwa-seok beo-no-reul hwa-gin-hae ju-se-yo'],
  ['표를 잃어버리지 마세요', 'Xin đừng làm mất vé.', 'pyo-reul ilh-eo-beo-ri-ji ma-se-yo'],
  ['개인 행동은 꼭 알려 주세요', 'Nếu tách đoàn, xin báo trước.', 'gae-in haeng-dong-eun kkok al-lyeo ju-se-yo'],
  ['비상약이 필요하신가요?', 'Quý khách có cần thuốc cơ bản không?', 'bi-sang-yak-i pi-ryo-ha-sin-ga-yo'],
  ['멀미하시면 앞자리에 앉으세요', 'Nếu say xe, xin ngồi ghế trước.', 'meol-mi-ha-si-myeon ap-ja-ri-e an-jeu-se-yo'],
  ['문제가 생기면 바로 말씀해 주세요', 'Nếu có vấn đề, xin báo ngay.', 'mun-je-ga saeng-gi-myeon ba-ro mal-sseum-hae ju-se-yo'],
  ['기념품은 여기서 사시면 됩니다', 'Quà lưu niệm có thể mua tại đây.', 'gi-nyeom-pum-eun yeo-gi-seo sa-si-myeon doem-ni-da'],
  ['가격 흥정은 제가 도와드릴게요', 'Tôi sẽ hỗ trợ mặc cả giá.', 'ga-gyeok heung-jeong-eun je-ga do-wa-deu-ril-ge-yo'],
  ['사진 촬영 금지 구역입니다', 'Đây là khu vực cấm chụp ảnh.', 'sa-jin chwal-yeong geum-ji gu-yeok-im-ni-da'],
  ['줄을 서서 입장해 주세요', 'Xin xếp hàng để vào cổng.', 'jul-eul seo-seo ip-jang-hae ju-se-yo'],
  ['천천히 이동해 주세요', 'Xin di chuyển chậm và cẩn thận.', 'cheon-cheon-hi i-dong-hae ju-se-yo'],
  ['지금은 자유 관람 시간입니다', 'Bây giờ là thời gian tham quan tự do.', 'ji-geum-eun ja-yu gwan-lam si-gan-im-ni-da'],
  ['정해진 시간에 꼭 돌아와 주세요', 'Xin quay lại đúng giờ quy định.', 'jeong-hae-jin si-gan-e kkok do-ra-wa ju-se-yo'],
  ['다음 설명은 버스에서 하겠습니다', 'Phần giới thiệu tiếp theo tôi sẽ nói trên xe.', 'da-eum seol-myeong-eun beo-seu-e-seo ha-ge-sseum-ni-da'],
  ['이 장소는 바람이 강합니다', 'Khu này gió khá mạnh.', 'i jang-so-neun ba-ram-i gang-ham-ni-da'],
  ['아이와 함께 계신 분은 손을 잡아 주세요', 'Đi cùng trẻ em xin nắm tay bé.', 'a-i-wa ham-kke gye-sin bun-eun son-eul ja-ba ju-se-yo'],
  ['단체 사진 먼저 찍겠습니다', 'Mình chụp ảnh đoàn trước nhé.', 'dan-che sa-jin meon-jeo jjik-get-seum-ni-da'],
  ['휴대품 관리를 부탁드립니다', 'Xin quý khách tự giữ đồ cá nhân.', 'hyu-dae-pum gwan-ri-reul bu-tak-deu-rim-ni-da']
];

const TOPIC_SPECIFIC = [
  {
    id: 'chao-hoi',
    name: 'Chào hỏi khách',
    phrases: [
      ['좋은 아침입니다', 'Chào buổi sáng ạ.', 'jo-eun a-chim-im-ni-da'],
      ['좋은 오후입니다', 'Chào buổi chiều ạ.', 'jo-eun o-hu-im-ni-da'],
      ['좋은 저녁입니다', 'Chào buổi tối ạ.', 'jo-eun jeo-nyeok-im-ni-da'],
      ['만나서 반갑습니다', 'Rất vui được gặp quý khách.', 'man-na-seo ban-gap-seum-ni-da'],
      ['오시느라 고생 많으셨습니다', 'Quý khách đã vất vả khi di chuyển đến đây.', 'o-si-neu-ra go-saeng manh-eu-syeot-seum-ni-da'],
      ['저는 오늘 담당 가이드입니다', 'Tôi là HDV phụ trách hôm nay.', 'jeo-neun o-neul dam-dang ga-i-deu-im-ni-da'],
      ['한국에서 오셨나요?', 'Quý khách đến từ Hàn Quốc phải không ạ?', 'han-guk-e-seo o-syeot-na-yo'],
      ['성함이 어떻게 되세요?', 'Quý khách tên là gì ạ?', 'seong-ham-i eo-tteo-ke doe-se-yo'],
      ['호칭은 어떻게 불러 드릴까요?', 'Tôi nên xưng hô với quý khách như thế nào?', 'ho-ching-eun eo-tteo-ke bul-leo deu-ril-kka-yo'],
      ['처음 뵙겠습니다', 'Rất hân hạnh được gặp lần đầu.', 'cheo-eum boep-get-seum-ni-da'],
      ['다낭에 오신 것을 환영합니다', 'Chào mừng quý khách đến Đà Nẵng.', 'da-nang-e o-sin geo-seul hwan-yeong-ham-ni-da'],
      ['편하게 말씀해 주세요', 'Quý khách cứ thoải mái trao đổi.', 'pyeon-ha-ge mal-sseum-hae ju-se-yo'],
      ['궁금한 점 언제든지 물어보세요', 'Có gì thắc mắc cứ hỏi bất kỳ lúc nào.', 'gung-geum-han jeom eon-je-deun-ji mu-reo-bo-se-yo'],
      ['오늘 잘 부탁드립니다', 'Rất mong được đồng hành cùng quý khách hôm nay.', 'o-neul jal bu-tak-deu-rim-ni-da'],
      ['팀원 모두 모이셨나요?', 'Mọi người trong đoàn đã tập trung đủ chưa?', 'ti-mwon mo-du mo-i-syeot-na-yo'],
      ['인원 확인하겠습니다', 'Tôi xin điểm danh số lượng khách.', 'in-won hwa-gin-ha-ge-sseum-ni-da'],
      ['편안한 여행 되시길 바랍니다', 'Chúc quý khách có chuyến đi thoải mái.', 'pyeon-an-han yeo-haeng doe-si-gil ba-ram-ni-da'],
      ['오늘 날씨가 좋아서 다행입니다', 'May quá hôm nay thời tiết đẹp.', 'o-neul nal-ssi-ga jo-a-seo da-haeng-im-ni-da'],
      ['한국어로 안내해 드리겠습니다', 'Tôi sẽ hướng dẫn bằng tiếng Hàn.', 'han-gu-geo-ro an-nae-hae deu-ri-ge-sseum-ni-da'],
      ['함께 즐거운 시간 보내요', 'Mình cùng có khoảng thời gian vui vẻ nhé.', 'ham-kke jeul-geo-un si-gan bo-nae-yo']
    ]
  },
  {
    id: 'san-bay',
    name: 'Đón khách ở sân bay',
    phrases: [
      ['입국 심사는 이쪽입니다', 'Khu vực kiểm tra nhập cảnh ở phía này.', 'ip-guk sim-sa-neun i-jjok-im-ni-da'],
      ['수하물 찾는 곳으로 가겠습니다', 'Mình đi tới khu lấy hành lý nhé.', 'su-ha-mul chat-neun go-seu-ro ga-ge-sseum-ni-da'],
      ['짐표를 확인해 주세요', 'Xin kiểm tra tem hành lý.', 'jim-pyo-reul hwa-gin-hae ju-se-yo'],
      ['트롤리를 가져다 드릴게요', 'Tôi sẽ lấy xe đẩy hành lý giúp quý khách.', 'teu-rol-li-reul ga-jyeo-da deu-ril-ge-yo'],
      ['세관 신고하실 물건이 있으세요?', 'Quý khách có đồ cần khai báo hải quan không?', 'se-gwan sin-go-ha-sil mul-geon-i i-sseu-se-yo'],
      ['환전이 필요하시면 도와드릴게요', 'Nếu cần đổi tiền, tôi sẽ hỗ trợ.', 'hwan-jeon-i pi-ryo-ha-si-myeon do-wa-deu-ril-ge-yo'],
      ['공항 와이파이를 연결해 드릴까요?', 'Tôi kết nối wifi sân bay giúp quý khách nhé?', 'gong-hang wa-i-pa-i-reul yeon-gyeol-hae deu-ril-kka-yo'],
      ['유심카드는 여기서 구매 가능합니다', 'SIM có thể mua ở đây.', 'yu-sim-ka-deu-neun yeo-gi-seo gu-mae ga-neung-ham-ni-da'],
      ['단체 버스는 밖에서 대기 중입니다', 'Xe đoàn đang đợi bên ngoài.', 'dan-che beo-seu-neun bak-kke-seo dae-gi jung-im-ni-da'],
      ['짐 개수를 다시 확인하겠습니다', 'Tôi xin kiểm tra lại số kiện hành lý.', 'jim gae-su-reul da-si hwa-gin-ha-ge-sseum-ni-da'],
      ['분실물이 있으면 바로 말씀해 주세요', 'Nếu thất lạc hành lý, xin báo ngay.', 'bun-sil-mul-i i-sseu-myeon ba-ro mal-sseum-hae ju-se-yo'],
      ['출구는 오른쪽입니다', 'Cửa ra ở bên phải.', 'chul-gu-neun o-reun-jjok-im-ni-da'],
      ['표지판을 따라오세요', 'Xin đi theo bảng chỉ dẫn.', 'pyo-ji-pan-eul tta-ra-o-se-yo'],
      ['여기서 잠깐 정리하겠습니다', 'Mình tạm dừng ở đây để sắp xếp đoàn.', 'yeo-gi-seo jam-kkan jeong-ri-ha-ge-sseum-ni-da'],
      ['차량 번호는 29번입니다', 'Biển số xe của đoàn là số 29.', 'cha-ryang beo-no-neun i-sip-gu-beon-im-ni-da'],
      ['기사님께 인사드리고 탑승하겠습니다', 'Mình chào tài xế rồi lên xe nhé.', 'gi-sa-nim-kke in-sa-deu-ri-go tap-seung-ha-ge-sseum-ni-da'],
      ['좌석은 자유롭게 앉으시면 됩니다', 'Quý khách chọn chỗ ngồi tự do.', 'jwa-seok-eun ja-yu-rop-ge an-jeu-si-myeon doem-ni-da'],
      ['에어컨 온도 괜찮으세요?', 'Nhiệt độ điều hòa có ổn không ạ?', 'e-eo-keon on-do gwaen-chanh-eu-se-yo'],
      ['먼저 호텔로 이동하겠습니다', 'Trước tiên chúng ta di chuyển về khách sạn.', 'meon-jeo ho-tel-lo i-dong-ha-ge-sseum-ni-da'],
      ['공항 이용 정말 수고 많으셨습니다', 'Quý khách đã rất vất vả ở sân bay.', 'gong-hang i-yong jeong-mal su-go manh-eu-syeot-seum-ni-da']
    ]
  },
  {
    id: 'lich-trinh',
    name: 'Giới thiệu lịch trình',
    phrases: [
      ['오늘 일정표를 나눠 드리겠습니다', 'Tôi sẽ phát lịch trình hôm nay.', 'o-neul il-jeong-pyo-reul na-nwo deu-ri-ge-sseum-ni-da'],
      ['오전에는 시내 관광을 합니다', 'Buổi sáng chúng ta tham quan trong thành phố.', 'o-jeon-e-neun si-nae gwan-gwang-eul ham-ni-da'],
      ['점심은 현지 식당에서 드십니다', 'Bữa trưa sẽ dùng tại nhà hàng địa phương.', 'jeom-sim-eun hyeon-ji sik-dang-e-seo deu-sim-ni-da'],
      ['오후에는 바나힐을 방문합니다', 'Buổi chiều mình tham quan Bà Nà Hills.', 'o-hu-e-neun ba-na-hil-eul bang-mun-ham-ni-da'],
      ['저녁에는 한강 야경을 보겠습니다', 'Buổi tối xem cảnh đêm sông Hàn.', 'jeo-nyeok-e-neun han-gang ya-gyeong-eul bo-ge-sseum-ni-da'],
      ['각 장소마다 설명 시간이 있습니다', 'Mỗi điểm sẽ có thời gian thuyết minh.', 'gak jang-so-ma-da seol-myeong si-gan-i i-sseum-ni-da'],
      ['자유시간도 충분히 드리겠습니다', 'Tôi sẽ dành đủ thời gian tự do cho quý khách.', 'ja-yu-si-gan-do chung-bun-hi deu-ri-ge-sseum-ni-da'],
      ['일정표 사진을 찍어 두세요', 'Xin chụp lại lịch trình để tiện theo dõi.', 'il-jeong-pyo sa-jin-eul jji-geo du-se-yo'],
      ['시간 변경이 있으면 바로 안내합니다', 'Nếu đổi giờ tôi sẽ báo ngay.', 'si-gan byeon-gyeong-i i-sseu-myeon ba-ro an-nae-ham-ni-da'],
      ['늦으시면 다음 일정에 영향이 있습니다', 'Nếu trễ sẽ ảnh hưởng lịch tiếp theo.', 'neu-jeu-si-myeon da-eum il-jeong-e yeong-hyang-i i-sseum-ni-da'],
      ['오늘 이동 거리는 약 오십 킬로입니다', 'Tổng quãng đường hôm nay khoảng 50km.', 'o-neul i-dong geo-ri-neun yak o-sip kil-lo-im-ni-da'],
      ['각 관광지 입장권은 제가 준비했습니다', 'Vé vào các điểm tôi đã chuẩn bị.', 'gak gwan-gwang-ji ip-jang-gwon-eun je-ga jun-bi-haet-seum-ni-da'],
      ['현지 사정에 따라 순서가 바뀔 수 있습니다', 'Thứ tự điểm có thể đổi tùy tình hình thực tế.', 'hyeon-ji sa-jeong-e tta-ra sun-seo-ga ba-kkwil su i-sseum-ni-da'],
      ['버스 안에서 다음 장소를 설명드리겠습니다', 'Tôi sẽ giới thiệu điểm tiếp theo trên xe.', 'beo-seu an-e-seo da-eum jang-so-reul seol-myeong-deu-ri-ge-sseum-ni-da'],
      ['사진 명소는 별도로 안내해 드릴게요', 'Điểm check-in đẹp tôi sẽ báo riêng.', 'sa-jin myeong-so-neun byeol-do-ro an-nae-hae deu-ril-ge-yo'],
      ['화장실 휴식은 두 번 예정되어 있습니다', 'Hôm nay có 2 lần nghỉ vệ sinh.', 'hwa-jang-sil hyu-sik-eun du beon ye-jeong-doe-eo i-sseum-ni-da'],
      ['우천 시에는 실내 코스로 변경합니다', 'Nếu mưa sẽ đổi sang lộ trình trong nhà.', 'u-cheon si-e-neun sil-nae ko-seu-ro byeon-gyeong-ham-ni-da'],
      ['일정 종료는 저녁 아홉 시입니다', 'Kết thúc lịch trình vào 9 giờ tối.', 'il-jeong jong-ryo-neun jeo-nyeok a-hop si-im-ni-da'],
      ['마지막 일정 후 호텔까지 모셔다 드립니다', 'Sau điểm cuối tôi sẽ đưa về khách sạn.', 'ma-ji-mak il-jeong hu ho-tel-kka-ji mo-syeo-da deu-rim-ni-da'],
      ['편안하고 안전한 일정으로 진행하겠습니다', 'Tôi sẽ điều hành lịch trình an toàn và thoải mái.', 'pyeon-an-ha-go an-jeon-han il-jeong-eu-ro jin-haeng-ha-ge-sseum-ni-da']
    ]
  },
  {
    id: 'nhac-gio',
    name: 'Nhắc giờ giấc',
    phrases: [
      ['지금 시간 확인해 주세요', 'Xin quý khách kiểm tra giờ hiện tại.', 'ji-geum si-gan hwa-gin-hae ju-se-yo'],
      ['십 분 뒤에 출발합니다', '10 phút nữa chúng ta xuất phát.', 'sip bun dwi-e chul-bal-ham-ni-da'],
      ['오 분 전에 미리 모여 주세요', 'Xin tập trung trước 5 phút.', 'o bun jeon-e mi-ri mo-yeo ju-se-yo'],
      ['약속 시간은 세 시 삼십 분입니다', 'Giờ hẹn là 3 giờ 30.', 'yak-sok si-gan-eun se si sam-sip bun-im-ni-da'],
      ['지각하시면 전화 부탁드립니다', 'Nếu đến muộn, xin gọi cho tôi.', 'ji-gak-ha-si-myeon jeon-hwa bu-tak-deu-rim-ni-da'],
      ['시간이 거의 다 되었습니다', 'Đã gần đến giờ rồi ạ.', 'si-gan-i geo-ui da doe-eot-seum-ni-da'],
      ['이제 이동 준비해 주세요', 'Xin chuẩn bị để di chuyển.', 'i-je i-dong jun-bi-hae ju-se-yo'],
      ['지금부터 집합 시간입니다', 'Bây giờ là giờ tập trung.', 'ji-geum-bu-teo ji-bap si-gan-im-ni-da'],
      ['늦으면 다음 코스가 짧아집니다', 'Nếu trễ thì thời gian điểm sau sẽ ngắn lại.', 'neu-jeu-myeon da-eum ko-seu-ga jjal-ba-jim-ni-da'],
      ['정시에 출발하겠습니다', 'Chúng ta sẽ xuất phát đúng giờ.', 'jeong-si-e chul-bal-ha-ge-sseum-ni-da'],
      ['휴식은 십오 분만 가능합니다', 'Thời gian nghỉ chỉ 15 phút thôi.', 'hyu-sik-eun sip-o bun-man ga-neung-ham-ni-da'],
      ['남은 시간은 오 분입니다', 'Còn lại 5 phút.', 'na-meun si-gan-eun o bun-im-ni-da'],
      ['곧 버스로 돌아와 주세요', 'Xin quay lại xe ngay nhé.', 'got beo-seu-ro do-ra-wa ju-se-yo'],
      ['시계를 맞춰 두시면 좋습니다', 'Quý khách nên chỉnh đồng hồ cùng giờ.', 'si-gye-reul mat-chwo du-si-myeon jo-seum-ni-da'],
      ['저와 같은 시간 기준으로 움직여 주세요', 'Xin đi theo mốc giờ của tôi.', 'jeo-wa ga-teun si-gan gi-jun-eu-ro um-jik-yeo ju-se-yo'],
      ['자유시간 종료 이 분 전입니다', 'Còn 2 phút là hết giờ tự do.', 'ja-yu-si-gan jong-ryo i bun jeon-im-ni-da'],
      ['이동 시간이 길어서 바로 출발합니다', 'Vì quãng đường dài nên ta đi ngay.', 'i-dong si-gan-i gil-eo-seo ba-ro chul-bal-ham-ni-da'],
      ['정해진 시간 엄수 부탁드립니다', 'Xin hợp tác đúng giờ đã quy định.', 'jeong-hae-jin si-gan eom-su bu-tak-deu-rim-ni-da'],
      ['다음 모임 시간은 카톡으로 보내드릴게요', 'Tôi sẽ gửi giờ hẹn tiếp theo qua KakaoTalk.', 'da-eum mo-im si-gan-eun ka-tok-eu-ro bo-nae-deu-ril-ge-yo'],
      ['시간 관리에 협조해 주셔서 감사합니다', 'Cảm ơn quý khách đã hợp tác đúng giờ.', 'si-gan gwan-ri-e hyeop-jo-hae ju-syeo-seo gam-sa-ham-ni-da']
    ]
  },
  {
    id: 'len-xe',
    name: 'Lên xe / xuống xe',
    phrases: [
      ['버스에 탑승해 주세요', 'Xin mời quý khách lên xe.', 'beo-seu-e tap-seung-hae ju-se-yo'],
      ['천천히 한 줄로 올라오세요', 'Xin lên xe từ từ theo hàng một.', 'cheon-cheon-hi han jul-lo ol-la-o-se-yo'],
      ['문 쪽에 서 계시면 위험합니다', 'Đứng gần cửa xe sẽ nguy hiểm.', 'mun jjok-e seo gye-si-myeon wi-heom-ham-ni-da'],
      ['좌석에 앉아 안전벨트를 매 주세요', 'Xin ngồi vào ghế và thắt dây an toàn.', 'jwa-seok-e an-ja an-jeon-bel-teu-reul mae ju-se-yo'],
      ['창문 밖으로 손을 내밀지 마세요', 'Xin đừng đưa tay ra ngoài cửa sổ.', 'chang-mun bak-eu-ro son-eul nae-mil-ji ma-se-yo'],
      ['정차 후에 내리겠습니다', 'Xe dừng hẳn rồi mình mới xuống.', 'jeong-cha hu-e nae-ri-ge-sseum-ni-da'],
      ['내릴 때 발밑 조심하세요', 'Xuống xe xin cẩn thận bước chân.', 'nae-ril ttae bal-mit jo-sim-ha-se-yo'],
      ['짐은 먼저 제가 내려 드릴게요', 'Hành lý để tôi lấy xuống trước cho quý khách.', 'jim-eun meon-jeo je-ga nae-ryeo deu-ril-ge-yo'],
      ['차량 번호를 기억해 주세요', 'Xin nhớ biển số xe của đoàn.', 'cha-ryang beo-no-reul gi-eok-hae ju-se-yo'],
      ['기사님이 문을 열어 주실 때까지 기다려 주세요', 'Xin chờ tài xế mở cửa rồi hãy xuống.', 'gi-sa-nim-i mun-eul yeo-reo ju-sil ttae-kka-ji gi-da-ryeo ju-se-yo'],
      ['비 오는 날에는 미끄러우니 조심하세요', 'Ngày mưa sàn trơn, xin cẩn thận.', 'bi o-neun nal-e-neun mi-kkeu-reo-u-ni jo-sim-ha-se-yo'],
      ['차 안에서는 이동하지 마세요', 'Khi xe chạy xin đừng đi lại trong xe.', 'cha an-e-seo-neun i-dong-ha-ji ma-se-yo'],
      ['휴게소에서는 정해진 시간에 돌아와 주세요', 'Ở trạm dừng xin quay lại đúng giờ.', 'hyu-ge-so-e-seo-neun jeong-hae-jin si-gan-e do-ra-wa ju-se-yo'],
      ['버스 앞쪽에 저를 따라오세요', 'Xin theo tôi ở phía đầu xe.', 'beo-seu ap-jjok-e jeo-reul tta-ra-o-se-yo'],
      ['오늘은 같은 좌석을 이용해 주세요', 'Hôm nay xin ngồi cố định một chỗ.', 'o-neul-eun ga-teun jwa-seok-eul i-yong-hae ju-se-yo'],
      ['차량 내부는 금연입니다', 'Trong xe cấm hút thuốc.', 'cha-ryang nae-bu-neun geum-yeon-im-ni-da'],
      ['음식물은 뚜껑을 닫아 주세요', 'Đồ ăn/uống xin đậy nắp lại.', 'eum-sik-mul-eun ttu-kkeong-eul da-da ju-se-yo'],
      ['하차 전에 소지품 확인해 주세요', 'Trước khi xuống xe xin kiểm tra đồ cá nhân.', 'ha-cha jeon-e so-ji-pum hwa-gin-hae ju-se-yo'],
      ['차가 출발하니 자리에 앉아 주세요', 'Xe sắp chạy, xin ngồi vào ghế.', 'cha-ga chul-bal-ha-ni ja-ri-e an-ja ju-se-yo'],
      ['내릴 때는 제 안내를 따라 주세요', 'Khi xuống xe xin theo hướng dẫn của tôi.', 'nae-ril ttae-neun je an-nae-reul tta-ra ju-se-yo']
    ]
  },
  {
    id: 'an-uong',
    name: 'Ăn uống',
    phrases: [
      ['메뉴판을 먼저 보시겠어요?', 'Quý khách xem menu trước nhé?', 'me-nyu-pan-eul meon-jeo bo-si-get-seo-yo'],
      ['맵지 않은 음식으로 추천해 드릴까요?', 'Tôi gợi ý món không cay nhé?', 'maep-ji a-neun eum-sik-eu-ro chu-cheon-hae deu-ril-kka-yo'],
      ['해산물 알레르기 있으세요?', 'Quý khách có dị ứng hải sản không?', 'hae-san-mul al-le-reu-gi i-sseu-se-yo'],
      ['채식 메뉴도 준비 가능합니다', 'Nhà hàng có chuẩn bị món chay.', 'chae-sik me-nyu-do jun-bi ga-neung-ham-ni-da'],
      ['음식이 뜨거우니 조심하세요', 'Món ăn nóng, xin cẩn thận.', 'eum-sik-i tteu-geo-u-ni jo-sim-ha-se-yo'],
      ['베트남 전통 음식입니다', 'Đây là món truyền thống Việt Nam.', 'be-teu-nam jeon-tong eum-sik-im-ni-da'],
      ['고수는 빼 드릴 수 있습니다', 'Có thể bỏ rau mùi nếu quý khách muốn.', 'go-su-neun ppae deu-ril su i-sseum-ni-da'],
      ['얼음은 넣어 드릴까요?', 'Tôi thêm đá cho quý khách nhé?', 'eo-reum-eun neo-eo deu-ril-kka-yo'],
      ['식사 시간은 한 시간입니다', 'Thời gian ăn là 1 tiếng.', 'sik-sa si-gan-eun han si-gan-im-ni-da'],
      ['추가 주문 도와드릴게요', 'Tôi hỗ trợ gọi thêm món.', 'chu-ga ju-mun do-wa-deu-ril-ge-yo'],
      ['물은 무료로 제공됩니다', 'Nước lọc được phục vụ miễn phí.', 'mul-eun mu-ryo-ro je-gong-doem-ni-da'],
      ['매운 음식 잘 드세요?', 'Quý khách ăn cay có được không?', 'mae-un eum-sik jal deu-se-yo'],
      ['아이용 메뉴도 있습니다', 'Có cả thực đơn cho trẻ em.', 'a-i-yong me-nyu-do i-sseum-ni-da'],
      ['천천히 드시고 나오시면 됩니다', 'Quý khách cứ ăn từ từ rồi ra.', 'cheon-cheon-hi deu-si-go na-o-si-myeon doem-ni-da'],
      ['식당 안에서는 금연입니다', 'Trong nhà hàng cấm hút thuốc.', 'sik-dang an-e-seo-neun geum-yeon-im-ni-da'],
      ['계산은 제가 도와드리겠습니다', 'Tôi sẽ hỗ trợ thanh toán.', 'gye-san-eun je-ga do-wa-deu-ri-ge-sseum-ni-da'],
      ['카드 결제 가능합니다', 'Có thể thanh toán bằng thẻ.', 'ka-deu gyeol-je ga-neung-ham-ni-da'],
      ['현금 결제도 가능합니다', 'Cũng có thể thanh toán tiền mặt.', 'hyeon-geum gyeol-je-do ga-neung-ham-ni-da'],
      ['영수증 필요하시면 말씀해 주세요', 'Nếu cần hóa đơn xin báo tôi.', 'yeong-su-jeung pi-ryo-ha-si-myeon mal-sseum-hae ju-se-yo'],
      ['맛이 어떠세요?', 'Món ăn có hợp khẩu vị không ạ?', 'ma-si eo-tteo-se-yo']
    ]
  },
  {
    id: 'khach-san',
    name: 'Khách sạn',
    phrases: [
      ['체크인 시간은 오후 두 시입니다', 'Giờ nhận phòng là 2 giờ chiều.', 'che-keu-in si-gan-eun o-hu du si-im-ni-da'],
      ['체크아웃 시간은 오전 열두 시입니다', 'Giờ trả phòng là 12 giờ trưa.', 'che-keu-a-ut si-gan-eun o-jeon yeol-du si-im-ni-da'],
      ['여권을 프런트에 보여 주세요', 'Xin xuất trình hộ chiếu tại quầy lễ tân.', 'yeo-gwon-eul peu-reon-teu-e bo-yeo ju-se-yo'],
      ['객실 키를 받아 주세요', 'Xin nhận chìa khóa/thẻ phòng.', 'gaek-sil ki-reul ba-da ju-se-yo'],
      ['엘리베이터는 오른쪽에 있습니다', 'Thang máy ở bên phải.', 'el-li-be-i-teo-neun o-reun-jjok-e i-sseum-ni-da'],
      ['조식은 칠 층 레스토랑입니다', 'Bữa sáng ở nhà hàng tầng 7.', 'jo-sik-eun chil cheung re-seu-to-rang-im-ni-da'],
      ['와이파이 비밀번호는 여기 있습니다', 'Mật khẩu wifi ở đây.', 'wa-i-pa-i bi-mil-beon-ho-neun yeo-gi i-sseum-ni-da'],
      ['미니바는 유료입니다', 'Mini bar tính phí.', 'mi-ni-ba-neun yu-ryo-im-ni-da'],
      ['룸서비스는 이 번호로 연락하세요', 'Room service gọi theo số này.', 'rum-seo-bi-seu-neun i beo-no-ro yeol-lak-ha-se-yo'],
      ['세탁 서비스도 이용 가능합니다', 'Có thể dùng dịch vụ giặt ủi.', 'se-tak seo-bi-seu-do i-yong ga-neung-ham-ni-da'],
      ['늦은 체크아웃은 추가 요금이 있습니다', 'Trả phòng muộn sẽ có phụ phí.', 'neu-jeun che-keu-a-ut-eun chu-ga yo-geum-i i-sseum-ni-da'],
      ['에어컨 온도는 이 버튼으로 조절하세요', 'Điều chỉnh điều hòa bằng nút này.', 'e-eo-keon on-do-neun i beo-teun-eu-ro jo-jeol-ha-se-yo'],
      ['온수는 항상 사용 가능합니다', 'Nước nóng luôn sẵn sàng.', 'on-su-neun hang-sang sa-yong ga-neung-ham-ni-da'],
      ['수건이 더 필요하시면 말씀해 주세요', 'Nếu cần thêm khăn, xin báo lễ tân.', 'su-geon-i deo pi-ryo-ha-si-myeon mal-sseum-hae ju-se-yo'],
      ['비상구 위치를 확인해 주세요', 'Xin kiểm tra vị trí cửa thoát hiểm.', 'bi-sang-gu wi-chi-reul hwa-gin-hae ju-se-yo'],
      ['객실에서 흡연은 금지입니다', 'Trong phòng cấm hút thuốc.', 'gaek-sil-e-seo heup-yeon-eun geum-ji-im-ni-da'],
      ['귀중품은 금고에 보관해 주세요', 'Xin để đồ quý vào két sắt.', 'gwi-jung-pum-eun geum-go-e bo-gwan-hae ju-se-yo'],
      ['문단속 꼭 해 주세요', 'Xin nhớ khóa cửa cẩn thận.', 'mun-dan-sok kkok hae ju-se-yo'],
      ['내일 아침 로비에서 만나겠습니다', 'Sáng mai mình gặp ở sảnh.', 'nae-il a-chim ro-bi-e-seo man-na-ge-sseum-ni-da'],
      ['편히 쉬시고 내일 뵙겠습니다', 'Quý khách nghỉ ngơi nhé, mai gặp lại.', 'pyeon-hi swi-si-go nae-il boep-get-seum-ni-da']
    ]
  },
  {
    id: 'hoi-an',
    name: 'Tham quan Hội An',
    phrases: [
      ['여기는 호이안 구시가지입니다', 'Đây là khu phố cổ Hội An.', 'yeo-gi-neun ho-i-an gu-si-ga-ji-im-ni-da'],
      ['노란 벽이 사진 명소입니다', 'Bức tường vàng là điểm chụp ảnh đẹp.', 'no-ran byeok-i sa-jin myeong-so-im-ni-da'],
      ['일본 다리는 저 앞에 있습니다', 'Chùa Cầu Nhật Bản ở phía trước.', 'il-bon da-ri-neun jeo ap-e i-sseum-ni-da'],
      ['등불 거리는 밤에 더 아름답습니다', 'Phố đèn lồng đẹp hơn vào buổi tối.', 'deung-bul geo-ri-neun bam-e deo a-reum-dap-seum-ni-da'],
      ['전통 의상 대여도 가능합니다', 'Có thể thuê trang phục truyền thống.', 'jeon-tong ui-sang dae-yeo-do ga-neung-ham-ni-da'],
      ['강변 산책은 자유롭게 하세요', 'Quý khách có thể đi dạo bờ sông tự do.', 'gang-byeon san-chaek-eun ja-yu-rop-ge ha-se-yo'],
      ['소원등 체험 원하시면 알려 주세요', 'Nếu muốn thả hoa đăng xin báo tôi.', 'so-won-deung che-heom won-ha-si-myeon al-lyeo ju-se-yo'],
      ['현지 시장은 저쪽 골목입니다', 'Chợ địa phương ở ngõ phía kia.', 'hyeon-ji si-jang-eun jeo-jjok gol-mok-im-ni-da'],
      ['사진 찍기 좋은 시간이 지금입니다', 'Giờ này chụp ảnh rất đẹp.', 'sa-jin jjik-gi jo-eun si-gan-i ji-geum-im-ni-da'],
      ['골목길이 좁으니 천천히 걸어 주세요', 'Đường hẻm hẹp, xin đi chậm.', 'gol-mok-gil-i jo-beu-ni cheon-cheon-hi geo-reo ju-se-yo'],
      ['자전거와 오토바이를 조심하세요', 'Xin cẩn thận xe đạp và xe máy.', 'ja-jeon-geo-wa o-to-ba-i-reul jo-sim-ha-se-yo'],
      ['현지 문화재를 만지지 마세요', 'Xin đừng chạm vào di tích.', 'hyeon-ji mun-hwa-jae-reul man-ji-ji ma-se-yo'],
      ['입장권은 제가 가지고 있습니다', 'Vé tham quan tôi đang giữ.', 'ip-jang-gwon-eun je-ga ga-ji-go i-sseum-ni-da'],
      ['집합 장소는 강변 카페 앞입니다', 'Điểm tập trung là trước quán cà phê ven sông.', 'ji-bap jang-so-neun gang-byeon ka-pe ap-im-ni-da'],
      ['야시장 구경 시간은 삼십 분입니다', 'Thời gian tham quan chợ đêm là 30 phút.', 'ya-si-jang gu-gyeong si-gan-eun sam-sip bun-im-ni-da'],
      ['기념품은 흥정이 가능합니다', 'Quà lưu niệm có thể trả giá.', 'gi-nyeom-pum-eun heung-jeong-i ga-neung-ham-ni-da'],
      ['현금 소액을 준비하시면 편합니다', 'Nên chuẩn bị tiền mặt mệnh giá nhỏ.', 'hyeon-geum so-aeg-eul jun-bi-ha-si-myeon pyeon-ham-ni-da'],
      ['보트 탑승 시 구명조끼를 입어 주세요', 'Khi đi thuyền xin mặc áo phao.', 'bo-teu tap-seung si gu-myeong-jo-kki-reul i-beo ju-se-yo'],
      ['돌아오는 시간 꼭 지켜 주세요', 'Xin nhớ giờ quay lại.', 'do-ra-o-neun si-gan kkok ji-kyeo ju-se-yo'],
      ['호이안 투어 즐겁게 마무리하겠습니다', 'Mình kết thúc tour Hội An thật vui nhé.', 'ho-i-an tu-eo jeul-geop-ge ma-mu-ri-ha-ge-sseum-ni-da']
    ]
  },
  {
    id: 'bana',
    name: 'Bà Nà Hills',
    phrases: [
      ['바나힐 케이블카로 올라가겠습니다', 'Chúng ta sẽ đi cáp treo lên Bà Nà Hills.', 'ba-na-hil ke-i-beul-ka-ro ol-la-ga-ge-sseum-ni-da'],
      ['케이블카 탑승권을 준비해 주세요', 'Xin chuẩn bị vé cáp treo.', 'ke-i-beul-ka tap-seung-gwon-eul jun-bi-hae ju-se-yo'],
      ['줄이 길 수 있으니 함께 이동해 주세요', 'Hàng có thể dài, xin đi cùng đoàn.', 'jul-i gil su i-sseu-ni ham-kke i-dong-hae ju-se-yo'],
      ['고도가 높아 기온이 낮습니다', 'Độ cao lớn nên nhiệt độ thấp hơn.', 'go-do-ga nop-a gi-on-i nat-seum-ni-da'],
      ['겉옷을 꼭 챙기세요', 'Xin nhớ mang áo khoác.', 'geod-o-seul kkok chaeng-gi-se-yo'],
      ['골든브릿지는 여기서 십 분 거리입니다', 'Cầu Vàng cách đây khoảng 10 phút đi bộ.', 'gol-deun-beu-rit-ji-neun yeo-gi-seo sip bun geo-ri-im-ni-da'],
      ['포토존에서 차례대로 사진 찍겠습니다', 'Mình chụp ảnh lần lượt tại điểm check-in.', 'po-to-jon-e-seo cha-rye-dae-ro sa-jin jjik-get-seum-ni-da'],
      ['놀이기구는 대기 시간이 깁니다', 'Trò chơi có thời gian chờ khá lâu.', 'no-ri-gi-gu-neun dae-gi si-gan-i gim-ni-da'],
      ['실내 게임존도 이용 가능합니다', 'Khu game trong nhà cũng có thể trải nghiệm.', 'sil-nae ge-im-jon-do i-yong ga-neung-ham-ni-da'],
      ['프렌치 빌리지는 자유 관람입니다', 'Làng Pháp tham quan tự do.', 'peu-ren-chi bil-li-ji-neun ja-yu gwan-lam-im-ni-da'],
      ['점심 식당은 정상 근처입니다', 'Nhà hàng trưa ở gần khu đỉnh núi.', 'jeom-sim sik-dang-eun jeong-sang geun-cheo-im-ni-da'],
      ['날씨가 변덕스러우니 우산을 준비하세요', 'Thời tiết thay đổi nhanh, xin chuẩn bị ô.', 'nal-ssi-ga byeon-deok-seu-reo-u-ni u-san-eul jun-bi-ha-se-yo'],
      ['안개가 짙으면 시야가 제한됩니다', 'Nếu sương mù dày thì tầm nhìn hạn chế.', 'an-gae-ga jit-eu-myeon si-ya-ga je-han-doem-ni-da'],
      ['하산 시간은 다섯 시입니다', 'Giờ xuống núi là 5 giờ.', 'ha-san si-gan-eun da-seot si-im-ni-da'],
      ['지정된 장소에서 모이겠습니다', 'Chúng ta tập trung tại điểm đã hẹn.', 'ji-jeong-doen jang-so-e-seo mo-i-ge-sseum-ni-da'],
      ['놀이기구 이용 시 안전수칙을 지켜 주세요', 'Khi chơi trò chơi xin tuân thủ quy định an toàn.', 'no-ri-gi-gu i-yong si an-jeon-su-chik-eul ji-kyeo ju-se-yo'],
      ['휴대폰을 단단히 잡아 주세요', 'Xin giữ chắc điện thoại khi di chuyển.', 'hyu-dae-pon-eul dan-dan-hi ja-ba ju-se-yo'],
      ['케이블카 안에서는 자리 이동을 삼가 주세요', 'Trong cabin cáp treo xin hạn chế đi lại.', 'ke-i-beul-ka an-e-seo-neun ja-ri i-dong-eul sam-ga ju-se-yo'],
      ['바나힐 일정 종료 후 다낭으로 내려갑니다', 'Kết thúc lịch Bà Nà chúng ta về lại Đà Nẵng.', 'ba-na-hil il-jeong jong-ryo hu da-nang-eu-ro nae-ryeo-gam-ni-da'],
      ['오늘 바나힐 추억 많이 담아 가세요', 'Chúc quý khách có nhiều kỷ niệm đẹp ở Bà Nà.', 'o-neul ba-na-hil chu-eok manh-i dam-a ga-se-yo']
    ]
  },
  {
    id: 'linh-ung',
    name: 'Chùa Linh Ứng',
    phrases: [
      ['여기는 린응사입니다', 'Đây là chùa Linh Ứng.', 'yeo-gi-neun lin-eung-sa-im-ni-da'],
      ['사찰 예절을 지켜 주세요', 'Xin giữ nghi lễ nơi chùa.', 'sa-chal ye-jeol-eul ji-kyeo ju-se-yo'],
      ['큰 소리로 말하지 마세요', 'Xin đừng nói to.', 'keun so-ri-ro mal-ha-ji ma-se-yo'],
      ['모자는 벗고 들어가 주세요', 'Xin bỏ mũ trước khi vào điện.', 'mo-ja-neun beot-go deu-reo-ga ju-se-yo'],
      ['짧은 옷은 피하시는 것이 좋습니다', 'Nên tránh trang phục quá ngắn.', 'jjal-beun o-seun pi-ha-si-neun geo-si jo-seum-ni-da'],
      ['불상을 향해 손가락질하지 마세요', 'Xin không chỉ tay vào tượng Phật.', 'bul-sang-eul hyang-hae son-ga-rak-jil-ha-ji ma-se-yo'],
      ['사진은 허용된 곳에서만 찍어 주세요', 'Chỉ chụp ảnh ở khu vực cho phép.', 'sa-jin-eun heo-yong-doen go-seo-man jji-geo ju-se-yo'],
      ['향을 피울 때는 조심해 주세요', 'Khi thắp hương xin cẩn thận.', 'hyang-eul pi-ul ttae-neun jo-sim-hae ju-se-yo'],
      ['계단이 많으니 천천히 이동하세요', 'Nhiều bậc thang, xin đi chậm.', 'gye-dan-i manh-eu-ni cheon-cheon-hi i-dong-ha-se-yo'],
      ['관광객이 많아 소지품 주의하세요', 'Khách đông, xin giữ kỹ đồ cá nhân.', 'gwan-gwang-gaek-i manh-a so-ji-pum ju-ui-ha-se-yo'],
      ['바다 전망이 아주 좋습니다', 'View biển ở đây rất đẹp.', 'ba-da jeon-mang-i a-ju jot-seum-ni-da'],
      ['해수관음상은 다낭의 상징입니다', 'Tượng Quan Âm là biểu tượng của Đà Nẵng.', 'hae-su-gwan-eum-sang-eun da-nang-ui sang-jing-im-ni-da'],
      ['기도 시간에는 조용히 기다려 주세요', 'Khi có giờ lễ xin chờ yên lặng.', 'gi-do si-gan-e-neun jo-yong-hi gi-da-ryeo ju-se-yo'],
      ['쓰레기를 버리지 마세요', 'Xin không xả rác.', 'sseu-re-gi-reul beo-ri-ji ma-se-yo'],
      ['신발 정리는 입구에서 해 주세요', 'Xin sắp xếp giày dép ở lối vào.', 'sin-bal jeong-ri-neun ip-gu-e-seo hae ju-se-yo'],
      ['전망대에서 단체 사진 찍겠습니다', 'Mình chụp ảnh đoàn ở điểm ngắm cảnh nhé.', 'jeon-mang-dae-e-seo dan-che sa-jin jjik-get-seum-ni-da'],
      ['바람이 강하니 모자 조심하세요', 'Gió mạnh, xin giữ mũ cẩn thận.', 'ba-ram-i gang-ha-ni mo-ja jo-sim-ha-se-yo'],
      ['종교 시설이니 예의를 부탁드립니다', 'Đây là cơ sở tôn giáo, mong quý khách giữ phép lịch sự.', 'jong-gyo si-seol-i-ni ye-ui-reul bu-tak-deu-rim-ni-da'],
      ['관람 후 주차장으로 이동하겠습니다', 'Sau khi tham quan xong ta di chuyển về bãi xe.', 'gwan-lam hu ju-cha-jang-eu-ro i-dong-ha-ge-sseum-ni-da'],
      ['편안한 마음으로 둘러보세요', 'Xin tham quan với tâm thế nhẹ nhàng.', 'pyeon-an-han ma-eum-eu-ro dul-leo-bo-se-yo']
    ]
  },
  {
    id: 'mua-sam',
    name: 'Mua sắm',
    phrases: [
      ['이곳은 정찰제 매장입니다', 'Đây là cửa hàng niêm yết giá.', 'i-go-seun jeong-chal-je mae-jang-im-ni-da'],
      ['가격표를 꼭 확인해 주세요', 'Xin kiểm tra bảng giá trước.', 'ga-gyeok-pyo-reul kkok hwa-gin-hae ju-se-yo'],
      ['원하시면 흥정을 도와드릴게요', 'Nếu cần tôi hỗ trợ trả giá.', 'won-ha-si-myeon heung-jeong-eul do-wa-deu-ril-ge-yo'],
      ['카드 결제 가능한지 먼저 확인하겠습니다', 'Tôi kiểm tra trước xem có quẹt thẻ được không.', 'ka-deu gyeol-je ga-neung-han-ji meon-jeo hwa-gin-ha-ge-sseum-ni-da'],
      ['환불 규정을 확인해 주세요', 'Xin xem kỹ chính sách đổi trả.', 'hwan-bul gyu-jeong-eul hwa-gin-hae ju-se-yo'],
      ['진품 여부를 꼭 체크하세요', 'Xin nhớ kiểm tra hàng chính hãng.', 'jin-pum yeo-bu-reul kkok che-keu-ha-se-yo'],
      ['영수증은 반드시 보관해 주세요', 'Xin giữ hóa đơn cẩn thận.', 'yeong-su-jeung-eun ban-deu-si bo-gwan-hae ju-se-yo'],
      ['기념품 포장해 드릴까요?', 'Tôi nhờ shop gói quà lưu niệm nhé?', 'gi-nyeom-pum po-jang-hae deu-ril-kka-yo'],
      ['현지 특산품은 이쪽에 있습니다', 'Đặc sản địa phương ở khu này.', 'hyeon-ji teuk-san-pum-eun i-jjok-e i-sseum-ni-da'],
      ['유통기한을 확인해 주세요', 'Xin kiểm tra hạn sử dụng.', 'yu-tong-gi-han-eul hwa-gin-hae ju-se-yo'],
      ['너무 싼 상품은 주의하세요', 'Hàng quá rẻ thì nên cẩn thận.', 'neo-mu ssan sang-pum-eun ju-ui-ha-se-yo'],
      ['공항 반입 가능한지 확인해 주세요', 'Xin kiểm tra có mang lên máy bay được không.', 'gong-hang ban-ip ga-neung-han-ji hwa-gin-hae ju-se-yo'],
      ['현금은 나눠서 보관하세요', 'Tiền mặt nên chia ra cất nhiều chỗ.', 'hyeon-geum-eun na-nwo-seo bo-gwan-ha-se-yo'],
      ['귀중품은 제가 있는 곳에서만 확인하세요', 'Xin kiểm tra đồ quý khi có tôi bên cạnh.', 'gwi-jung-pum-eun je-ga it-neun go-seo-man hwa-gin-ha-se-yo'],
      ['쇼핑 시간은 사십 분입니다', 'Thời gian mua sắm là 40 phút.', 'syo-ping si-gan-eun sa-sip bun-im-ni-da'],
      ['정해진 시간에 버스로 돌아와 주세요', 'Xin quay lại xe đúng giờ đã hẹn.', 'jeong-hae-jin si-gan-e beo-seu-ro do-ra-wa ju-se-yo'],
      ['포장 박스가 필요하시면 말씀해 주세요', 'Nếu cần hộp đóng gói xin báo tôi.', 'po-jang bak-seu-ga pi-ryo-ha-si-myeon mal-sseum-hae ju-se-yo'],
      ['택스 리펀드는 공항에서 가능합니다', 'Hoàn thuế có thể làm ở sân bay.', 'taek-seu ri-peon-deu-neun gong-hang-e-seo ga-neung-ham-ni-da'],
      ['구매 수량을 확인하고 결제하세요', 'Xin kiểm tra số lượng trước khi thanh toán.', 'gu-mae su-ryang-eul hwa-gin-ha-go gyeol-je-ha-se-yo'],
      ['즐거운 쇼핑 되세요', 'Chúc quý khách mua sắm vui vẻ.', 'jeul-geo-un syo-ping doe-se-yo']
    ]
  },
  {
    id: 'tinh-huong',
    name: 'Xử lý tình huống',
    phrases: [
      ['침착하게 말씀해 주세요', 'Xin bình tĩnh trao đổi với tôi.', 'chim-chak-ha-ge mal-sseum-hae ju-se-yo'],
      ['제가 바로 확인하겠습니다', 'Tôi sẽ kiểm tra ngay lập tức.', 'je-ga ba-ro hwa-gin-ha-ge-sseum-ni-da'],
      ['지금 위치를 알려 주세요', 'Xin cho tôi vị trí hiện tại.', 'ji-geum wi-chi-reul al-lyeo ju-se-yo'],
      ['전화 연결이 안 되면 문자 주세요', 'Nếu không gọi được, xin nhắn tin.', 'jeon-hwa yeon-gyeol-i an doe-myeon mun-ja ju-se-yo'],
      ['여권을 잃어버리셨나요?', 'Quý khách bị mất hộ chiếu đúng không?', 'yeo-gwon-eul ilh-eo-beo-ri-syeot-na-yo'],
      ['경찰서에 함께 가겠습니다', 'Tôi sẽ đi cùng quý khách tới đồn cảnh sát.', 'gyeong-chal-seo-e ham-kke ga-ge-sseum-ni-da'],
      ['병원 통역을 도와드리겠습니다', 'Tôi sẽ hỗ trợ phiên dịch ở bệnh viện.', 'byeong-won tong-yeok-eul do-wa-deu-ri-ge-sseum-ni-da'],
      ['약국에서 필요한 약을 찾겠습니다', 'Tôi sẽ giúp tìm thuốc cần thiết ở nhà thuốc.', 'yak-guk-e-seo pi-ryo-han yag-eul chat-get-seum-ni-da'],
      ['현금 분실 시 카드부터 정지하세요', 'Nếu mất tiền/thẻ, xin khóa thẻ trước.', 'hyeon-geum bun-sil si ka-deu-bu-teo jeong-ji-ha-se-yo'],
      ['긴급 연락처는 이 번호입니다', 'Số liên hệ khẩn cấp là số này.', 'gin-geup yeol-lak-cheo-neun i beo-no-im-ni-da'],
      ['사고가 나면 먼저 안전한 곳으로 이동하세요', 'Nếu có sự cố, trước tiên hãy vào nơi an toàn.', 'sa-go-ga na-myeon meon-jeo an-jeon-han go-seu-ro i-dong-ha-se-yo'],
      ['응급차가 오고 있습니다', 'Xe cấp cứu đang tới.', 'eung-geup-cha-ga o-go i-sseum-ni-da'],
      ['증상을 자세히 말씀해 주세요', 'Xin mô tả rõ triệu chứng.', 'jeung-sang-eul ja-se-hi mal-sseum-hae ju-se-yo'],
      ['보험 서류를 확인하겠습니다', 'Tôi sẽ kiểm tra giấy tờ bảo hiểm.', 'bo-heom seo-ryu-reul hwa-gin-ha-ge-sseum-ni-da'],
      ['분실 장소를 다시 가보겠습니다', 'Mình sẽ quay lại điểm có thể làm rơi đồ.', 'bun-sil jang-so-reul da-si ga-bo-ge-sseum-ni-da'],
      ['단체 안전을 위해 잠시 대기해 주세요', 'Vì an toàn đoàn, xin chờ một chút.', 'dan-che an-jeon-eul wi-hae jam-si dae-gi-hae ju-se-yo'],
      ['문제가 해결될 때까지 함께하겠습니다', 'Tôi sẽ đồng hành tới khi xử lý xong vấn đề.', 'mun-je-ga hae-gyeol-doel ttae-kka-ji ham-kke-ha-ge-sseum-ni-da'],
      ['호텔 프런트와 연락 중입니다', 'Tôi đang liên hệ lễ tân khách sạn.', 'ho-tel peu-reon-teu-wa yeol-lak jung-im-ni-da'],
      ['번역 앱으로도 도와드릴게요', 'Tôi sẽ hỗ trợ thêm bằng app dịch.', 'beon-yeok a-beu-ro-do do-wa-deu-ril-ge-yo'],
      ['걱정하지 마세요, 제가 끝까지 도와드릴게요', 'Xin đừng lo, tôi sẽ hỗ trợ tới cùng.', 'geok-jeong-ha-ji ma-se-yo je-ga kkeut-kka-ji do-wa-deu-ril-ge-yo']
    ]
  },
  {
    id: 'tam-biet',
    name: 'Tạm biệt khách',
    phrases: [
      ['오늘 함께해 주셔서 감사합니다', 'Cảm ơn quý khách đã đồng hành hôm nay.', 'o-neul ham-kke-hae ju-syeo-seo gam-sa-ham-ni-da'],
      ['여행이 즐거우셨길 바랍니다', 'Hy vọng chuyến đi mang lại niềm vui cho quý khách.', 'yeo-haeng-i jeul-geo-u-syeot-gil ba-ram-ni-da'],
      ['다낭에서 좋은 추억 많이 만드셨나요?', 'Quý khách đã có nhiều kỷ niệm đẹp ở Đà Nẵng chứ?', 'da-nang-e-seo jo-eun chu-eok manh-i man-deu-syeot-na-yo'],
      ['호이안도 마음에 드셨나요?', 'Hội An có làm quý khách hài lòng không ạ?', 'ho-i-an-do ma-eum-e deu-syeot-na-yo'],
      ['다음에 가족과 또 오세요', 'Lần sau mời quý khách quay lại cùng gia đình.', 'da-eum-e ga-jok-gwa tto o-se-yo'],
      ['공항까지 안전하게 모셔다 드리겠습니다', 'Tôi sẽ đưa quý khách ra sân bay an toàn.', 'gong-hang-kka-ji an-jeon-ha-ge mo-syeo-da deu-ri-ge-sseum-ni-da'],
      ['귀국 비행 시간 다시 확인해 주세요', 'Xin kiểm tra lại giờ bay về Hàn Quốc.', 'gwi-guk bi-haeng si-gan da-si hwa-gin-hae ju-se-yo'],
      ['여권과 탑승권 챙기셨나요?', 'Quý khách đã mang hộ chiếu và boarding pass chưa?', 'yeo-gwon-gwa tap-seung-gwon chaeng-gi-syeot-na-yo'],
      ['수하물 무게도 확인해 주세요', 'Xin kiểm tra cân nặng hành lý.', 'su-ha-mul mu-ge-do hwa-gin-hae ju-se-yo'],
      ['면세점 이용 시간 충분합니다', 'Quý khách có đủ thời gian mua sắm ở duty free.', 'myeon-se-jeom i-yong si-gan chung-bun-ham-ni-da'],
      ['문제가 생기면 바로 연락 주세요', 'Nếu có vấn đề xin liên hệ ngay.', 'mun-je-ga saeng-gi-myeon ba-ro yeol-lak ju-se-yo'],
      ['한국 도착 후에도 건강하세요', 'Chúc quý khách khỏe mạnh sau khi về Hàn Quốc.', 'han-guk do-chak hu-e-do geon-gang-ha-se-yo'],
      ['다음 베트남 여행도 함께하고 싶습니다', 'Hy vọng lần tới lại được đồng hành cùng quý khách.', 'da-eum be-teu-nam yeo-haeng-do ham-kke-ha-go sip-seum-ni-da'],
      ['후기 남겨 주시면 큰 도움이 됩니다', 'Nếu để lại đánh giá sẽ giúp tôi rất nhiều.', 'hu-gi nam-gyeo ju-si-myeon keun do-um-i doem-ni-da'],
      ['사진은 단톡방에 공유해 드릴게요', 'Tôi sẽ chia sẻ ảnh vào nhóm chat.', 'sa-jin-eun dan-tok-bang-e gong-yu-hae deu-ril-ge-yo'],
      ['오늘 일정 정말 수고 많으셨습니다', 'Hôm nay quý khách đã rất vất vả.', 'o-neul il-jeong jeong-mal su-go manh-eu-syeot-seum-ni-da'],
      ['안전한 귀가 되시길 바랍니다', 'Chúc quý khách về nhà an toàn.', 'an-jeon-han gwi-ga doe-si-gil ba-ram-ni-da'],
      ['또 만날 날을 기다리겠습니다', 'Mong sớm gặp lại quý khách.', 'tto man-nal na-reul gi-da-ri-ge-sseum-ni-da'],
      ['진심으로 감사드립니다', 'Tôi chân thành cảm ơn quý khách.', 'jin-sim-eu-ro gam-sa-deu-rim-ni-da'],
      ['안녕히 가세요', 'Tạm biệt và thượng lộ bình an.', 'an-nyeong-hi ga-se-yo']
    ]
  }
];

function buildFiftyPhrases(topicId, specificPhrases) {
  const used = new Set(specificPhrases.map(([ko]) => ko));
  const merged = [...specificPhrases];

  for (const phrase of GENERAL_COMMON_PHRASES) {
    if (merged.length >= 50) break;
    if (used.has(phrase[0])) continue;
    merged.push(phrase);
    used.add(phrase[0]);
  }

  return merged.slice(0, 50).map(([ko, vi, roman], index) => ({
    id: `${topicId}-${index + 1}`,
    ko,
    vi,
    roman,
    note: index < specificPhrases.length ? 'Thực chiến theo chủ đề.' : 'Cụm từ thông dụng người Hàn dùng nhiều khi đi tour.'
  }));
}

const PHRASE_TOPICS = TOPIC_SPECIFIC.map(topic => ({
  id: topic.id,
  name: topic.name,
  phrases: buildFiftyPhrases(topic.id, topic.phrases)
}));
